const express = require('express');
const path = require('path');
const fs = require('fs');
const compression = require('compression');

const app = express();
const PORT = process.env.PORT || 8080;

// Configuración para entornos detrás de proxy inverso
app.set('trust proxy', true);

// 1. VERSIÓN DINÁMICA — generada una sola vez al arrancar Node.js
const APP_VERSION = Date.now().toString();

// 2. COMPRESIÓN GZIP/BROTLI
app.use(compression());

// 3. MIDDLEWARE i18n — DETECTOR DE DOMINIO
app.use((req, res, next) => {
    const host = req.hostname || req.get('host') || req.headers.host || '';

    console.log(`\n--- [i18n] ---`);
    console.log(`Host: "${host}"`);

    let lang = 'en'; // Default .tech
    if (host.includes('.es')) {
        lang = 'es';
    }

    res.locals.lang = lang;
    console.log(`Lang: ${lang.toUpperCase()}`);
    console.log(`--------------\n`);

    // Anti-cache para el HTML (los assets tienen su propio header)
    res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate');

    next();
});

// 4. SERVICIO INTELIGENTE DE WebP
app.use((req, res, next) => {
    if (req.accepts('webp') && req.url.match(/\.(png|jpg|jpeg)$/i)) {
        const webpPath = path.join(__dirname, 'dist', req.url.replace(/\.(png|jpg|jpeg)$/i, '.webp'));
        fs.access(webpPath, fs.constants.F_OK, (err) => {
            if (!err) {
                res.setHeader('Vary', 'Accept');
                return res.sendFile(webpPath);
            }
            next();
        });
    } else {
        next();
    }
});

// 5. CABECERAS DE CACHÉ PARA ASSETS ESTÁTICOS
const cacheStatic = (res, filePath) => {
    if (filePath.match(/\.(html|sw\.js|service-worker\.js|manifest\.json)$/)) {
        res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
        res.setHeader('Pragma', 'no-cache');
        res.setHeader('Expires', '0');
    } else if (filePath.match(/\.(js|css|webp|png|jpg|jpeg|woff2)$/)) {
        res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
    }
};

app.use(express.static(path.join(__dirname, 'dist'), {
    setHeaders: cacheStatic,
    etag: true,
    lastModified: true
}));

// 6. SPA FALLBACK — Serve the correct pre-built HTML per domain
//
//   dist/index.html     → EN metadata (kinetora.tech) — built by Vite
//   dist/index.es.html  → ES metadata (kinetora.es)  — generated by scripts/postbuild-seo.mjs
//
//   Both files have static, fully resolved metadata (no {{}} placeholders).
//   The server performs only lightweight runtime overrides:
//     - lang attribute on <html>
//     - i18n-bridge script (for React I18nProvider)
//     - canonical / og:url / og:locale (domain-aware)
//     - hreflang SSR deduplication
//
app.get('*', (req, res) => {
    const lang = res.locals.lang || 'en';
    const isES = lang === 'es';

    // Select the correct pre-built file
    const htmlFile = isES ? 'index.es.html' : 'index.html';
    const indexPath = path.join(__dirname, 'dist', htmlFile);

    // Fallback to index.html if index.es.html doesn't exist yet (first deploy before postbuild ran)
    const finalPath = fs.existsSync(indexPath)
        ? indexPath
        : path.join(__dirname, 'dist', 'index.html');

    fs.readFile(finalPath, 'utf8', (err, data) => {
        if (err) {
            return res.status(500).send('Error loading HTML');
        }

        let html = data;

        // ── Cache busting for local assets only (skip external URLs) ──────────
        html = html.replace(
            /((?:href|src)=")(?!\/|http|https|\/\/)([^"]+\.(?:css|js))"/g,
            `$1$2?v=${APP_VERSION}"`
        );

        // ── Inject correct lang attribute on <html> ────────────────────────────
        html = html.replace(/<html[^>]*>/, `<html lang="${lang}">`);

        // ── Inject i18n-bridge for I18nProvider.tsx ────────────────────────────
        // index.es.html already has it baked in — update the value to be safe.
        if (!html.includes('id="i18n-bridge"')) {
            html = html.replace('<head>', `<head>\n    <script id="i18n-bridge">window.__KINETORA_LANG__ = "${lang}";</script>`);
        } else {
            html = html.replace(
                /<script id="i18n-bridge">window\.__KINETORA_LANG__ = "[^"]*";<\/script>/,
                `<script id="i18n-bridge">window.__KINETORA_LANG__ = "${lang}";</script>`
            );
        }

        // ── Runtime canonical + og:url + og:locale override ───────────────────
        const canonicalUrl = isES ? 'https://kinetora.es/' : 'https://kinetora.tech/';
        const ogLocale     = isES ? 'es_ES' : 'en_US';

        html = html
            .replace(/(<link rel="canonical" href=")[^"]*(")/g, `$1${canonicalUrl}$2`)
            .replace(/(property="og:url" content=")[^"]*(")/g,    `$1${canonicalUrl}$2`)
            .replace(/(property="og:locale" content=")[^"]*(")/g, `$1${ogLocale}$2`);

        // ── Hreflang SSR — injected only if not already present (dedup) ────────
        if (!html.includes('data-seo-ssr="true"')) {
            const hreflangBlock = `
    <!-- Hreflang (SSR runtime): bidirectional signal for Google -->
    <link rel="alternate" hreflang="es"        href="https://kinetora.es/"   data-seo-ssr="true" />
    <link rel="alternate" hreflang="en"        href="https://kinetora.tech/" data-seo-ssr="true" />
    <link rel="alternate" hreflang="x-default" href="https://kinetora.tech/" data-seo-ssr="true" />`;
            html = html.replace('</head>', `${hreflangBlock}\n</head>`);
        }

        // ── Strict no-cache headers ────────────────────────────────────────────
        res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
        res.setHeader('Pragma', 'no-cache');
        res.setHeader('Expires', '0');
        res.setHeader('Content-Type', 'text/html; charset=utf-8');

        res.send(html);
    });
});

app.listen(PORT, () => {
    console.log(`🚀 Kinetora Elite Server [v${APP_VERSION}] running on port ${PORT}`);
    console.log(`   EN → dist/index.html    (kinetora.tech)`);
    console.log(`   ES → dist/index.es.html (kinetora.es)`);
});
