// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ezarpucfsasumwpcderw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6YXJwdWNmc2FzdW13cGNkZXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2NjYzMjMsImV4cCI6MjA4OTI0MjMyM30.forffo9V3esR25vOjDZHz_9NzKBo2kSB0NlHS6UxX2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);